# Generated by Django 4.0.3 on 2022-12-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='İsim')),
                ('typ', models.CharField(max_length=50, verbose_name='Türü')),
                ('categr', models.CharField(max_length=50, verbose_name='Kategori')),
            ],
        ),
    ]
